/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["MeController_updateName"];
        trace?: never;
    };
    "/moims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MoimController_list"];
        put?: never;
        post: operations["MoimController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MoimController_getOne"];
        put?: never;
        post?: never;
        delete: operations["MoimController_remove"];
        options?: never;
        head?: never;
        patch: operations["MoimController_updateMaxMembers"];
        trace?: never;
    };
    "/moims/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MoimController_getMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{id}/membership": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MoimController_leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{moimId}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MoimController_kick"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{moimId}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MoimController_transferOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{moimId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MoimInviteController_list"];
        put?: never;
        post: operations["MoimInviteController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{moimId}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["MoimInviteController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["InvitePublicController_checkValidity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{token}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["InviteAcceptController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ChatController_history"];
        put?: never;
        post: operations["ChatController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{id}/polls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PollController_list"];
        put?: never;
        post: operations["PollController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{id}/polls/{pollId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PollController_vote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/moims/{id}/polls/{pollId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PollController_close"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["DeviceTokenController_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["DeviceTokenController_unregister"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponseDto: {
            /**
             * @description 전체 헬스 상태
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @description 데이터베이스 연결성 결과
             * @example up
             * @enum {string}
             */
            db: "up" | "down";
        };
        ProfileResponseDto: {
            /**
             * @description Supabase auth user id(`sub`) — profile의 PK
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            id: string;
            /**
             * @description 사용자 표시 이름(미보유 시 null — 온보딩 가드 대상)
             * @example 홍길동
             */
            name: string | null;
            /**
             * @description profile 최초 생성 시각(ISO-8601)
             * @example 2026-06-02T09:59:34.000Z
             */
            createdAt: string;
        };
        UpdateNameDto: {
            /**
             * @description 설정할 사용자 표시 이름(trim 후 비어 있을 수 없음)
             * @example 홍길동
             */
            name: string;
        };
        CreateMoimDto: {
            /**
             * @description 모임 이름(비어 있을 수 없음)
             * @example 주말 등산 모임
             */
            name: string;
            /**
             * @description 생성자의 모임별 표시 이름(host nickname, 비어 있을 수 없음). owner 멤버십에 주입된다.
             * @example 호스트
             */
            nickname: string;
            /**
             * @description 이벤트 일정(ISO-8601, optional). 부재/빈 값이면 일정 미정.
             * @example 2026-07-01T10:00:00.000Z
             */
            startsAt?: string;
            /**
             * @description 이벤트 장소(자유 텍스트, optional).
             * @example 강남역 스타벅스
             */
            location?: string;
            /**
             * @description 모임 정원(optional, 기본 15). 1 이상의 정수.
             * @example 20
             */
            maxMembers?: number;
        };
        MoimResponseDto: {
            /**
             * @description 모임 id(uuid)
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            id: string;
            /**
             * @description 모임 이름
             * @example 주말 등산 모임
             */
            name: string;
            /**
             * @description 이벤트 일정(ISO-8601) 또는 null(일정 미정)
             * @example 2026-07-01T10:00:00.000Z
             */
            startsAt: string | null;
            /**
             * @description 이벤트 장소(자유 텍스트) 또는 null
             * @example 강남역 스타벅스
             */
            location: string | null;
            /**
             * @description 모임 정원(기본 15). 현재 멤버 수가 이 값 이상이면 신규 가입이 409로 거부된다.
             * @example 15
             */
            maxMembers: number;
            /**
             * @description 생성자 sub(= profile.id)
             * @example 00000000-0000-4000-8000-000000000001
             */
            createdBy: string;
            /**
             * @description 모임 생성 시각(ISO-8601)
             * @example 2026-06-13T00:00:00.000Z
             */
            createdAt: string;
        };
        MemberResponseDto: {
            /**
             * @description 멤버 sub(= profile.id)
             * @example 00000000-0000-4000-8000-000000000001
             */
            userId: string;
            /**
             * @description 모임별 표시 이름
             * @example 호스트
             */
            nickname: string;
            /**
             * @description 멤버 역할("owner" | "member")
             * @example owner
             */
            role: string;
            /**
             * @description 가입(생성) 시각(ISO-8601)
             * @example 2026-06-13T00:00:00.000Z
             */
            joinedAt: string;
        };
        UpdateMaxMembersDto: {
            /**
             * @description 수정할 모임 정원(1 이상의 정수). 현재 멤버 수 미만으로 낮춰도 소급 퇴장 없음(신규 가입만 차단).
             * @example 20
             */
            maxMembers: number;
        };
        TransferOwnerDto: {
            /**
             * @description 소유권을 이양받을 대상 멤버 userId(비어 있을 수 없음)
             * @example 00000000-0000-4000-8000-000000000002
             */
            userId: string;
        };
        CreateInviteDto: {
            /**
             * @description 만료 시각(ISO-8601). 미지정 시 발급 시점 +7일. 상한 +30일(초과 400).
             * @example 2026-06-21T00:00:00.000Z
             */
            expiresAt?: string;
            /**
             * @description 선택적 사용 횟수 제한(1 이상의 정수). 미지정 시 무제한.
             * @example 5
             */
            maxUses?: number;
        };
        InviteResponseDto: {
            /**
             * @description 초대 id(uuid)
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            id: string;
            /**
             * @description 대상 모임 id
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            moimId: string;
            /**
             * @description 추측 불가 초대 토큰(base64url, ≥128-bit). 수락 링크에 사용한다.
             * @example k3J9_aZ...base64url43chars
             */
            token: string;
            /**
             * @description 만료 시각(ISO-8601)
             * @example 2026-06-21T00:00:00.000Z
             */
            expiresAt: string;
            /**
             * @description 사용 횟수 제한(null이면 무제한)
             * @example 5
             */
            maxUses: number | null;
            /**
             * @description 현재 사용 횟수
             * @example 0
             */
            usedCount: number;
            /**
             * @description 폐기 시각(ISO-8601). null이면 미폐기(유효).
             * @example null
             */
            revokedAt: string | null;
            /**
             * @description 발급 시각(ISO-8601)
             * @example 2026-06-14T00:00:00.000Z
             */
            createdAt: string;
        };
        InviteValidityDto: {
            /**
             * @description 초대가 속한 모임 id
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            moimId: string;
        };
        AcceptInviteDto: {
            /**
             * @description 수락자의 모임별 표시 이름(비어 있을 수 없음)
             * @example 게스트1
             */
            nickname: string;
        };
        AcceptInviteResponseDto: {
            /**
             * @description 가입한 모임 id(웹 랜딩이 /moims/:id/chat 리다이렉트에 사용)
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            moimId: string;
        };
        SendMessageDto: {
            /**
             * @description 메시지 본문(비어 있을 수 없음, 최대 2000자)
             * @example 안녕하세요
             */
            content: string;
        };
        ChatMessageResponseDto: {
            /**
             * @description 메시지 id(BigInt PK의 문자열 표현 — 단조 증가, keyset 커서 기준)
             * @example 42
             */
            id: string;
            /**
             * @description 메시지가 속한 모임 id
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            moimId: string;
            /**
             * @description 발신자 sub(= profile.id). 표시 이름은 멤버 목록에서 클라이언트가 해석한다.
             * @example 00000000-0000-4000-8000-000000000001
             */
            senderId: string;
            /**
             * @description 메시지 본문
             * @example 안녕하세요
             */
            content: string;
            /**
             * @description 메시지 생성 시각(ISO-8601)
             * @example 2026-06-14T00:00:00.000Z
             */
            createdAt: string;
        };
        ChatHistoryResponseDto: {
            /** @description 커서 이전 최신순(내림차순) 메시지 목록 */
            messages: components["schemas"]["ChatMessageResponseDto"][];
            /**
             * @description 다음 페이지 커서(가장 오래된 반환분의 id). 더 없으면 null.
             * @example 37
             */
            nextCursor: string | null;
        };
        CreatePollDto: {
            /**
             * @description 투표 질문(trim 후 비어 있을 수 없음)
             * @example 다음 모임 날짜는?
             */
            question: string;
            /**
             * @description 선택지 라벨 배열(trim 후 비지 않은 항목 2개 이상 필요)
             * @example [
             *       "토요일",
             *       "일요일"
             *     ]
             */
            options: string[];
            /**
             * @description 여러 개 선택 허용 여부(poll 별 옵트인). true 면 다중 선택(토글), 생략/false 면 단일 선택(교체).
             * @default false
             * @example false
             */
            multiSelect: boolean;
            /**
             * @description 마감 시각(ISO-8601). 생략 시 null(마감 없음 — 영구히 열림). 무효 ISO 는 400 Bad Request.
             * @example 2026-06-25T12:00:00.000Z
             */
            closesAt?: string | null;
            /**
             * @description 투표 종류. "date" 면 options 가 ISO-8601 날짜 문자열 배열(옵션별 optionDate 저장), "place" 면 자유 텍스트 장소명(마감 시 승자 label → Moim.location). 생략/"general" 이면 일반 자유 텍스트 옵션.
             * @default general
             * @example general
             * @enum {string}
             */
            kind: "general" | "date" | "place";
        };
        PollOptionResponseDto: {
            /**
             * @description 선택지 id
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            id: string;
            /**
             * @description 선택지 라벨
             * @example 토요일
             */
            label: string;
            /**
             * @description 이 선택지의 득표 수(표 0 이면 0)
             * @example 3
             */
            voteCount: number;
            /**
             * @description 날짜 투표 옵션의 시각(ISO-8601). 일반 투표 옵션은 null.
             * @example 2026-06-27T12:00:00.000Z
             */
            optionDate: string | null;
        };
        PollResponseDto: {
            /**
             * @description 투표 id(uuid)
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            id: string;
            /**
             * @description 투표 질문
             * @example 다음 모임 날짜는?
             */
            question: string;
            /**
             * @description 생성자 sub(= profile.id)
             * @example 00000000-0000-4000-8000-000000000001
             */
            createdBy: string;
            /**
             * @description 투표 생성 시각(ISO-8601)
             * @example 2026-06-20T00:00:00.000Z
             */
            createdAt: string;
            /**
             * @description 여러 개 선택 허용 여부(true=다중 선택/토글, false=단일 선택/교체).
             * @example false
             */
            multiSelect: boolean;
            /**
             * @description 투표 종류. "general"=일반(자유 텍스트 옵션), "date"=날짜 투표(optionDate 있음), "place"=장소 투표(마감 시 승자 → location).
             * @example general
             * @enum {string}
             */
            kind: "general" | "date" | "place";
            /** @description 선택지 목록(각 선택지의 득표 수 + optionDate 포함) */
            options: components["schemas"]["PollOptionResponseDto"][];
            /**
             * @description 호출자 자신이 고른 선택지 id 목록(미투표 시 빈 배열). 단일 선택은 0/1요소, 다중 선택은 0..N요소.
             * @example [
             *       "15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8"
             *     ]
             */
            myVotes: string[];
            /**
             * @description 마감 시각(ISO-8601). null 이면 마감 없음(영구히 열림). 마감 판정은 isClosed 를 권위 있는 출처로 사용한다.
             * @example 2026-06-25T12:00:00.000Z
             */
            closesAt: string | null;
            /**
             * @description 서버 계산 마감 여부(closesAt != null AND closesAt <= 서버 now). 클라이언트 시계 오차 차단용 — 차단/배지 판정에 사용한다.
             * @example false
             */
            isClosed: boolean;
            /**
             * @description 자동 확정된 모임 일정(ISO-8601). 날짜 투표 마감 시 단일 최다 득표 옵션의 날짜가 Moim.startsAt 으로 설정된 경우에만 값이 있다. vote/list 응답에선 항상 null.
             * @example 2026-06-27T12:00:00.000Z
             */
            finalizedStartsAt: string | null;
            /**
             * @description 자동 확정된 모임 장소. 장소 투표 마감 시 단일 최다 득표 옵션의 장소명이 Moim.location 으로 설정된 경우에만 값이 있다. vote/list 응답·날짜 투표에선 null.
             * @example 강남역 2번 출구
             */
            finalizedLocation: string | null;
            /**
             * @description finalize 건너뛴 이유. "tie"=동점, "no_votes"=표 없음, null=finalize 성공 또는 일반 투표 또는 vote/list 응답.
             * @example null
             * @enum {string|null}
             */
            finalizeSkippedReason: "tie" | "no_votes" | null;
        };
        VoteDto: {
            /**
             * @description 선택지 id(해당 poll 에 속해야 함 — 아니면 400)
             * @example 15ebe4ba-7f12-4e2c-bfa4-a0a9eb5022b8
             */
            optionId: string;
        };
        RegisterDeviceDto: {
            /**
             * @description FCM/Expo 디바이스 push 토큰(비어 있을 수 없음)
             * @example ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]
             */
            token: string;
            /**
             * @description 디바이스 플랫폼(비어 있을 수 없음)
             * @example ios
             * @enum {string}
             */
            platform: "android" | "ios";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description DB 접속 가능 — 정상 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
            /** @description DB 접속 불가 — degraded */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
        };
    };
    MeController_getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 인증 사용자의 profile(최초 요청 시 자동 생성) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_updateName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNameDto"];
            };
        };
        responses: {
            /** @description 이름 갱신 후 갱신된 profile 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileResponseDto"];
                };
            };
            /** @description name이 비어 있음(trim 후) — 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 자신이 속한 모임 목록 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoimResponseDto"][];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMoimDto"];
            };
        };
        responses: {
            /** @description 모임 생성 + 생성자 owner 멤버십 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoimResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 단건 모임 정보(멤버 한정) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoimResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 멤버가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 존재하지 않는 모임 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 모임 삭제(owner 전용, Cascade) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 owner가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 존재하지 않는 모임 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_updateMaxMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMaxMembersDto"];
            };
        };
        responses: {
            /** @description 모임 정원 수정(owner 전용) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoimResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 owner가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 존재하지 않는 모임 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_getMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 목록(nickname 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberResponseDto"][];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 멤버가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 존재하지 않는 모임 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 탈퇴(owner 금지) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description owner는 탈퇴 불가 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 멤버십 부재(가입한 적 없음) — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_kick: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moimId: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 멤버 강제 퇴장(owner 전용) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 비-owner 또는 대상이 owner — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 모임 없음 또는 대상 멤버십 없음 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimController_transferOwner: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moimId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferOwnerDto"];
            };
        };
        responses: {
            /** @description 소유권 이양(owner → 대상 멤버) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 비-owner — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 모임 없음 또는 대상 멤버십 없음 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimInviteController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moimId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초대 목록(owner 전용, live 토큰 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponseDto"][];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 owner가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 존재하지 않는 모임 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimInviteController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moimId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            /** @description 초대 발급(owner 전용) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 owner가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 존재하지 않는 모임 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MoimInviteController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moimId: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 초대 폐기(owner 전용) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 owner가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 존재하지 않는 모임/초대 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InvitePublicController_checkValidity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 유효한 초대 — moimId 반환 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteValidityDto"];
                };
            };
            /** @description 미지 토큰 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 만료·폐기 토큰 — 410 */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    InviteAcceptController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteDto"];
            };
        };
        responses: {
            /** @description 초대 수락 + 멤버십 생성(멱등) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptInviteResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 미지 토큰 — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 사용 횟수 초과 — 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 만료·폐기 토큰 — 410 */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_history: {
        parameters: {
            query: {
                cursor: string;
                limit: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description keyset 내림차순(최신순) 히스토리 + nextCursor */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponseDto"];
                };
            };
            /** @description 잘못된 cursor — 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 멤버가 아님(또는 없는 모임) — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ChatController_send: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendMessageDto"];
            };
        };
        responses: {
            /** @description 메시지 전송 + 저장된 메시지 반환 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatMessageResponseDto"];
                };
            };
            /** @description 빈/과대 content — 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 멤버가 아님(또는 없는 모임) — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PollController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 모임의 투표 목록(옵션별 voteCount + multiSelect + 호출자 myVotes 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponseDto"][];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 멤버가 아님(또는 없는 모임) — 403/404 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PollController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePollDto"];
            };
        };
        responses: {
            /** @description 투표 생성 + 옵션(투표 0 직후 상태) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponseDto"];
                };
            };
            /** @description 빈 question / 유효 옵션 <2 / 무효 closesAt ISO / 미지 kind / 무효 날짜 옵션 ISO — 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 멤버가 아님(또는 없는 모임) — 403/404 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PollController_vote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pollId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoteDto"];
            };
        };
        responses: {
            /** @description 투표 기록/교체 + 갱신된 단건 poll 결과 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponseDto"];
                };
            };
            /** @description 빈 optionId / 해당 poll 의 선택지가 아닌 optionId — 400 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 대상 모임의 멤버가 아님 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 해당 모임에 속하지 않는(또는 없는) pollId — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 마감된 투표에 투표 시도 — 409 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PollController_close: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                pollId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 마감된 poll 결과(closesAt=now, isClosed:true, finalize 필드 포함) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PollResponseDto"];
                };
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 비멤버 또는 생성자가 아닌 멤버 — 403 */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 해당 모임에 속하지 않는(또는 없는) pollId — 404 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeviceTokenController_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceDto"];
            };
        };
        responses: {
            /** @description 디바이스 토큰 등록(upsert, 중복 없음) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeviceTokenController_unregister: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 디바이스 토큰 해제(소유자 한정, orphan token 방지) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 유효한 Supabase JWT 부재 — 401 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
